In [4]:
import numpy as np

In [4]:
arr = np.arange(0,10,1)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr2 = np.identity(3)
arr2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
arr3 = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [6]:
arr3.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr5 = np.reshape(arr4,(3,3))
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate([arr1,arr2], axis=0)
arr3

array([1, 2, 3, 4, 5, 6])

In [12]:
np.random.rand(5,5)

array([[0.4447495 , 0.12542077, 0.72262601, 0.03920366, 0.69188359],
       [0.64661915, 0.46937651, 0.92887569, 0.20177283, 0.07785177],
       [0.82980725, 0.62082685, 0.96388124, 0.85054564, 0.47683967],
       [0.86501238, 0.8240293 , 0.82801052, 0.50735299, 0.58246389],
       [0.60254363, 0.34835867, 0.83941939, 0.40589558, 0.18258664]])

In [14]:
np.max(np.random.randint(1,11, size = (5,5)))

10

In [15]:
arr = np.array([10, 20, 5, 40, 15])

In [21]:
a = np.where(arr == np.min(arr))[0][0]
a

2

In [22]:
np.linspace(5,15,50)

array([ 5.        ,  5.20408163,  5.40816327,  5.6122449 ,  5.81632653,
        6.02040816,  6.2244898 ,  6.42857143,  6.63265306,  6.83673469,
        7.04081633,  7.24489796,  7.44897959,  7.65306122,  7.85714286,
        8.06122449,  8.26530612,  8.46938776,  8.67346939,  8.87755102,
        9.08163265,  9.28571429,  9.48979592,  9.69387755,  9.89795918,
       10.10204082, 10.30612245, 10.51020408, 10.71428571, 10.91836735,
       11.12244898, 11.32653061, 11.53061224, 11.73469388, 11.93877551,
       12.14285714, 12.34693878, 12.55102041, 12.75510204, 12.95918367,
       13.16326531, 13.36734694, 13.57142857, 13.7755102 , 13.97959184,
       14.18367347, 14.3877551 , 14.59183673, 14.79591837, 15.        ])

In [23]:
arr = np.array([-3, -1, 0, 2, 4])

In [24]:
relu = np.where(arr <= 0, 0, arr)
relu

array([0, 0, 0, 2, 4])

In [25]:
arr = np.array([-2, 0, 2])
sigmoid = 1/(1 + np.exp(-arr))
sigmoid

array([0.11920292, 0.5       , 0.88079708])

In [ ]:
# Example inputs
Q = np.random.rand(2, 3, 4)  # (batch_size, seq_len, d_model)
K = np.random.rand(2, 3, 4)  # (batch_size, seq_len, d_model)
V = np.random.rand(2, 3, 4)  # (batch_size, seq_len, d_model)

# Compute scaled dot-product attention
d_k = Q.shape[-1]  # Dimension of the key
scores = np.matmul(Q, K.transpose(0, 2, 1)) / np.sqrt(d_k)  # (batch_size, seq_len, seq_len)

# Apply softmax to get attention weights
A = np.exp(scores - np.max(scores, axis=-1, keepdims=True))  # Shift values for numerical stability
A = A / np.sum(A, axis=-1, keepdims=True)  # Normalize to get probabilities

# Compute the attention output
Z = np.matmul(A, V)